import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { ArrowLeft, Check, Lock, Play, X, ExternalLink, StickyNote, FileQuestion, Sparkles, Trophy } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useServerFn } from "@tanstack/react-start";
import { aiGenerate } from "@/lib/ai.functions";
import ReactMarkdown from "react-markdown";

export const Route = createFileRoute("/_authenticated/app/ai/roadmap/$roadmapId")({
  component: RoadmapTree,
});

type Task = {
  id: string;
  node_key: string | null;
  title: string;
  description: string | null;
  difficulty: string | null;
  minutes: number;
  completed: boolean;
  youtube_video_id: string | null;
  youtube_title: string | null;
  youtube_channel: string | null;
  youtube_thumbnail: string | null;
  youtube_url: string | null;
  practice_task: string | null;
  notes: string | null;
  prereq_ids: string[] | null;
  position_x: number | null;
  position_y: number | null;
  order_index: number | null;
};

const CANVAS_W = 900;
const CANVAS_H = 1400;

function RoadmapTree() {
  const { roadmapId } = Route.useParams();
  const qc = useQueryClient();
  const [selected, setSelected] = useState<string | null>(null);
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const dragRef = useRef<{ x: number; y: number; px: number; py: number } | null>(null);
  const pinchRef = useRef<{ dist: number; zoom: number } | null>(null);
  const [generatingGuide, setGeneratingGuide] = useState(false);
  const callAi = useServerFn(aiGenerate);

  async function generateStudyGuide(taskId: string, topicTitle: string, description: string | null) {
    setGeneratingGuide(true);
    try {
      const prompt = `Write a comprehensive, easy-to-understand study guide and summary for the topic "${topicTitle}". ${description ? "Context: " + description : ""}
Find and summarize high-quality educational material and explanations online.
Format: Beautiful HTML with Tailwind CSS classes for rich styles, emojis, and clear explanations.
Rules:
1. Use standard HTML tags (div, h1, h2, h3, p, ul, li, strong, etc.).
2. Style with Tailwind CSS (e.g. text-indigo-900, bg-indigo-50/50, border-l-4, p-4, font-bold, list-disc, pl-5, space-y-2, etc.) to make it look premium and modern.
3. Incorporate friendly emojis throughout.
4. Keep it concise but comprehensive. Make sure it explains the core concept with an analogy and key takeaways.
5. Do NOT include html/markdown code blocks wrapper, just return raw HTML.`;
      
      const res = await callAi({ data: { prompt, system: "You are an expert study assistant. Output a beautifully designed study guide in raw HTML using Tailwind CSS styling and emojis." } });
      const guideHtml = res.text;
      
      localStorage.setItem(`guide:${taskId}`, guideHtml);
      
      toast.success("Study guide generated successfully!");
      qc.invalidateQueries({ queryKey: ["roadmap-tasks", roadmapId] });
    } catch (e) {
      toast.error("Failed to generate study guide: " + (e as Error).message);
    } finally {
      setGeneratingGuide(false);
    }
  }

  function printStudyGuide(title: string, htmlContent: string) {
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      toast.error("Please allow popups to download/print the study guide.");
      return;
    }
    
    const styledHtml = `
      <html>
        <head>
          <title>${title} - Study Guide</title>
          <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
          <style>
            @media print {
              body { font-size: 12pt; line-height: 1.6; }
              .no-print { display: none; }
            }
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; padding: 2rem; max-width: 800px; margin: 0 auto; }
          </style>
        </head>
        <body>
          <div class="flex justify-between items-center mb-6 border-b pb-4 no-print">
            <h1 class="text-sm font-bold text-gray-500 font-sans">Study Guide Preview</h1>
            <button onclick="window.print()" class="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded text-sm shadow font-sans">
              Print / Save as PDF
            </button>
          </div>
          <article class="prose max-w-none">
            <h1 class="text-3xl font-black mb-2 text-indigo-900 font-sans">${title}</h1>
            <p class="text-xs text-gray-500 mb-6 font-sans">Generated by StudySphere AI</p>
            <div class="text-sm leading-relaxed text-gray-800">${htmlContent}</div>
          </article>
          <script>
            setTimeout(() => { window.print(); }, 500);
          </script>
        </body>
      </html>
    `;
    printWindow.document.write(styledHtml);
    printWindow.document.close();
  }

  const { data: rm } = useQuery({
    queryKey: ["roadmap", roadmapId],
    queryFn: async () => (await supabase.from("ai_roadmaps").select("*").eq("id", roadmapId).maybeSingle()).data,
  });

  const { data: tasks = [] } = useQuery({
    queryKey: ["roadmap-tasks", roadmapId],
    queryFn: async () => (await supabase.from("ai_roadmap_tasks").select("*").eq("roadmap_id", roadmapId).order("order_index")).data as Task[] ?? [],
  });

  const byKey = useMemo(() => {
    const m: Record<string, Task> = {};
    for (const t of tasks) if (t.node_key) m[t.node_key] = t;
    return m;
  }, [tasks]);

  const unlocked = useMemo(() => {
    const s = new Set<string>();
    for (const t of tasks) {
      const prereqs = t.prereq_ids ?? [];
      if (prereqs.length === 0) s.add(t.id);
      else if (prereqs.every(k => byKey[k]?.completed)) s.add(t.id);
    }
    return s;
  }, [tasks, byKey]);

  const done = tasks.filter(t => t.completed).length;
  const pct = tasks.length ? Math.round((done / tasks.length) * 100) : 0;
  const remaining = tasks.length - done;
  const remMinutes = tasks.filter(t => !t.completed).reduce((s, t) => s + (t.minutes || 30), 0);
  const eta = remMinutes ? new Date(Date.now() + (remMinutes / 60 / 2) * 86400000) : null;
  const currentTask = tasks.find(t => !t.completed && unlocked.has(t.id));

  async function toggleComplete(id: string, completed: boolean) {
    await supabase.from("ai_roadmap_tasks").update({ completed: !completed }).eq("id", id);
    qc.invalidateQueries({ queryKey: ["roadmap-tasks", roadmapId] });
  }
  async function saveNotes(id: string, notes: string) {
    await supabase.from("ai_roadmap_tasks").update({ notes }).eq("id", id);
    qc.invalidateQueries({ queryKey: ["roadmap-tasks", roadmapId] });
  }

  const sel = selected ? tasks.find(t => t.id === selected) : null;

  function onWheel(e: React.WheelEvent) {
    e.preventDefault();
    setZoom(z => Math.max(0.5, Math.min(2.5, z - e.deltaY * 0.002)));
  }
  function onPointerDown(e: React.PointerEvent) {
    (e.target as HTMLElement).setPointerCapture?.(e.pointerId);
    dragRef.current = { x: e.clientX, y: e.clientY, px: pan.x, py: pan.y };
  }
  function onPointerMove(e: React.PointerEvent) {
    if (!dragRef.current) return;
    setPan({ x: dragRef.current.px + (e.clientX - dragRef.current.x), y: dragRef.current.py + (e.clientY - dragRef.current.y) });
  }
  function onPointerUp() { dragRef.current = null; }

  useEffect(() => {
    // center current node initially
    if (currentTask && tasks.length && pan.x === 0 && pan.y === 0) {
      const cx = (currentTask.position_x ?? 0.5) * CANVAS_W;
      const cy = (currentTask.position_y ?? 0.3) * CANVAS_H;
      setPan({ x: 180 - cx * zoom, y: 300 - cy * zoom });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentTask?.id]);

  return (
    <div className="fixed inset-0 flex flex-col bg-background">
      {/* Header */}
      <div className="relative z-10 border-b border-border bg-card/70 px-4 py-3 backdrop-blur-xl">
        <div className="flex items-center gap-3">
          <Link to="/app/ai/roadmap" className="grid h-9 w-9 place-items-center rounded-xl border border-border">
            <ArrowLeft className="h-4 w-4" />
          </Link>
          <div className="min-w-0 flex-1">
            <p className="truncate text-sm font-black">{rm?.name ?? rm?.exam ?? "Roadmap"}</p>
            <p className="text-[10px] text-muted-foreground">{done}/{tasks.length} topics · {pct}%{eta ? ` · ETA ${eta.toLocaleDateString()}` : ""}</p>
          </div>
          <div className="grid h-11 w-11 place-items-center">
            <ProgressRing pct={pct} />
          </div>
        </div>
        <div className="mt-2 h-1.5 w-full overflow-hidden rounded-full bg-muted">
          <div className="h-full gradient-brand transition-all duration-700" style={{ width: `${pct}%` }} />
        </div>
        <div className="mt-2 flex gap-2 text-[10px]">
          <Stat label="Done" val={done} tint="bg-success/10 text-success" />
          <Stat label="Remaining" val={remaining} tint="bg-primary/10 text-primary" />
          <Stat label="Hours" val={Math.round(remMinutes / 60)} tint="bg-warning/10 text-warning" />
        </div>
      </div>

      {/* Canvas */}
      <div
        className="relative flex-1 touch-none select-none overflow-hidden bg-gradient-to-b from-background via-background to-primary/5"
        onWheel={onWheel}
        onPointerDown={onPointerDown}
        onPointerMove={onPointerMove}
        onPointerUp={onPointerUp}
        onPointerCancel={onPointerUp}
      >
        {/* animated dot grid */}
        <div className="pointer-events-none absolute inset-0 opacity-30" style={{ backgroundImage: "radial-gradient(circle, oklch(0.72 0.19 295 / 0.25) 1px, transparent 1px)", backgroundSize: "24px 24px" }} />

        <div
          className="absolute origin-top-left"
          style={{ transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})`, width: CANVAS_W, height: CANVAS_H }}
        >
          <svg width={CANVAS_W} height={CANVAS_H} className="absolute inset-0 pointer-events-none">
            <defs>
              <linearGradient id="conn-done" x1="0" x2="1">
                <stop offset="0%" stopColor="oklch(0.75 0.17 155)" />
                <stop offset="100%" stopColor="oklch(0.72 0.19 295)" />
              </linearGradient>
              <linearGradient id="conn-open" x1="0" x2="1">
                <stop offset="0%" stopColor="oklch(0.72 0.19 295 / 0.6)" />
                <stop offset="100%" stopColor="oklch(0.78 0.18 210 / 0.6)" />
              </linearGradient>
            </defs>
            {tasks.flatMap(t => (t.prereq_ids ?? []).map(k => {
              const from = byKey[k]; if (!from) return null;
              const x1 = (from.position_x ?? 0.5) * CANVAS_W;
              const y1 = (from.position_y ?? 0.5) * CANVAS_H;
              const x2 = (t.position_x ?? 0.5) * CANVAS_W;
              const y2 = (t.position_y ?? 0.5) * CANVAS_H;
              const mx = (x1 + x2) / 2;
              const path = `M ${x1} ${y1} C ${mx} ${y1 + 60}, ${mx} ${y2 - 60}, ${x2} ${y2}`;
              const bothDone = from.completed && t.completed;
              const unlockedEdge = from.completed;
              return (
                <path
                  key={`${t.id}-${k}`}
                  d={path}
                  stroke={bothDone ? "url(#conn-done)" : unlockedEdge ? "url(#conn-open)" : "oklch(0.30 0.03 275 / 0.4)"}
                  strokeWidth={bothDone ? 3 : 2}
                  fill="none"
                  strokeDasharray={unlockedEdge ? "0" : "6 6"}
                  className={unlockedEdge && !bothDone ? "animate-pulse" : ""}
                />
              );
            })).filter(Boolean)}
          </svg>

          {tasks.map((t, i) => {
            const cx = (t.position_x ?? 0.5) * CANVAS_W;
            const cy = (t.position_y ?? i / tasks.length) * CANVAS_H;
            const isUnlocked = unlocked.has(t.id);
            const isCurrent = currentTask?.id === t.id;
            const bg = t.completed
              ? "bg-gradient-to-br from-emerald-500 to-teal-600 text-white shadow-[0_0_40px_rgba(52,211,153,0.5)]"
              : !isUnlocked
              ? "bg-muted text-muted-foreground opacity-50"
              : isCurrent
              ? "gradient-brand text-primary-foreground shadow-[0_0_40px_rgba(139,92,246,0.55)] animate-pulse"
              : "bg-card border border-border text-foreground";
            return (
              <button
                key={t.id}
                onClick={(e) => { e.stopPropagation(); setSelected(t.id); }}
                onPointerDown={(e) => e.stopPropagation()}
                className={`absolute -translate-x-1/2 -translate-y-1/2 rounded-2xl px-3 py-2.5 text-xs font-bold transition-transform hover:scale-105 ${bg}`}
                style={{ left: cx, top: cy, minWidth: 130, maxWidth: 180 }}
              >
                <div className="flex items-center gap-1.5">
                  {t.completed ? <Check className="h-3.5 w-3.5" /> : !isUnlocked ? <Lock className="h-3 w-3" /> : <span className="h-2 w-2 rounded-full bg-current opacity-70" />}
                  <span className="truncate">{t.title}</span>
                </div>
                <p className="mt-0.5 text-[9px] font-normal opacity-70">{t.difficulty} · {t.minutes}m</p>
              </button>
            );
          })}
        </div>

        {/* Zoom controls */}
        <div className="absolute right-3 top-3 flex flex-col gap-2">
          <button onClick={() => setZoom(z => Math.min(2.5, z + 0.2))} className="grid h-9 w-9 place-items-center rounded-xl border border-border bg-card/80 text-lg backdrop-blur">+</button>
          <button onClick={() => setZoom(z => Math.max(0.5, z - 0.2))} className="grid h-9 w-9 place-items-center rounded-xl border border-border bg-card/80 text-lg backdrop-blur">−</button>
          <button onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }); }} className="grid h-9 w-9 place-items-center rounded-xl border border-border bg-card/80 text-[10px] font-bold backdrop-blur">R</button>
        </div>

        {tasks.length === 0 && (
          <div className="absolute inset-0 grid place-items-center">
            <div className="text-center">
              <Sparkles className="mx-auto h-8 w-8 text-muted-foreground animate-pulse" />
              <p className="mt-2 text-sm text-muted-foreground">Loading roadmap…</p>
            </div>
          </div>
        )}

        {pct === 100 && tasks.length > 0 && (
          <div className="pointer-events-none absolute inset-x-0 top-4 mx-auto w-max rounded-full bg-gradient-to-r from-emerald-500 to-teal-500 px-4 py-2 text-xs font-bold text-white shadow-lg animate-fade-in">
            <Trophy className="mr-1 inline h-3.5 w-3.5" /> Completed!
          </div>
        )}
      </div>

      {/* Detail Panel */}
      {sel && (() => {
        const prereqs = (sel.prereq_ids ?? []).map(k => byKey[k]).filter(Boolean);
        const studyGuide = localStorage.getItem(`guide:${sel.id}`) || null;
        const progressState = sel.completed ? "Completed" : unlocked.has(sel.id) ? "In Progress" : "Locked";
        const progressColor = sel.completed
          ? "bg-emerald-500/15 text-emerald-500 border-emerald-500/20"
          : unlocked.has(sel.id)
          ? "bg-violet-500/15 text-violet-500 border-violet-500/20"
          : "bg-muted text-muted-foreground border-muted-foreground/20";
        return (
          <div className="absolute inset-0 z-50 flex items-end md:items-stretch md:justify-end bg-black/60 backdrop-blur-sm animate-fade-in" onClick={() => setSelected(null)}>
            <div onClick={(e) => e.stopPropagation()} className="w-full md:w-96 md:max-w-md rounded-t-3xl md:rounded-t-none md:rounded-l-3xl border-t md:border-t-0 md:border-l border-border bg-card p-5 shadow-2xl animate-slide-in-right max-h-[85vh] md:max-h-full overflow-y-auto">
              <div className="mx-auto mb-3 h-1 w-10 rounded-full bg-muted" />
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1">
                  <div className="flex flex-wrap items-center gap-1.5">
                    <span className={"rounded-full px-2 py-0.5 text-[10px] font-bold uppercase " + (sel.difficulty === "advanced" ? "bg-destructive/10 text-destructive" : sel.difficulty === "intermediate" ? "bg-warning/10 text-warning" : "bg-success/10 text-success")}>{sel.difficulty ?? "beginner"}</span>
                    <span className="text-[10px] text-muted-foreground">⏱️ {sel.minutes} mins</span>
                    <span className={`rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider ${progressColor}`}>
                      {progressState}
                    </span>
                  </div>
                  <h2 className="mt-2 text-xl font-black">{sel.title}</h2>
                  {sel.description && <p className="mt-1 text-sm text-muted-foreground">{sel.description}</p>}
                </div>
                <button onClick={() => setSelected(null)} className="grid h-9 w-9 place-items-center rounded-xl border border-border"><X className="h-4 w-4" /></button>
              </div>

              {/* Completion checkbox */}
              <div className="mt-4 flex items-center gap-3 rounded-2xl border border-border bg-background p-3.5">
                <input
                  type="checkbox"
                  id="completion-checkbox"
                  checked={sel.completed}
                  onChange={() => toggleComplete(sel.id, sel.completed)}
                  className="h-5 w-5 rounded border-border text-primary focus:ring-primary accent-[color:var(--brand)] cursor-pointer"
                />
                <label htmlFor="completion-checkbox" className="flex-1 cursor-pointer">
                  <p className="text-xs font-bold text-foreground">Mark as Completed</p>
                  <p className="text-[11px] text-muted-foreground">Keep track of your study progress</p>
                </label>
              </div>

              {/* AI Study Guide */}
              {studyGuide ? (
                <div className="mt-4 rounded-2xl border border-border bg-background p-4 text-left">
                  <div className="flex items-center justify-between border-b border-border pb-2 mb-3">
                    <div className="flex items-center gap-1.5">
                      <Sparkles className="h-3.5 w-3.5 text-primary" />
                      <p className="text-[10px] font-bold uppercase text-muted-foreground tracking-wider">AI Study Guide</p>
                    </div>
                    <button
                      onClick={() => printStudyGuide(sel.title, studyGuide || "")}
                      className="flex items-center gap-1 text-[10px] font-bold text-primary hover:underline"
                    >
                      📄 Save / Print PDF
                    </button>
                  </div>
                  <div
                    className="text-sm leading-relaxed text-foreground select-text"
                    dangerouslySetInnerHTML={{ __html: studyGuide }}
                  />
                </div>
              ) : (
                <div className="mt-4 rounded-2xl border border-dashed border-border bg-background p-5 text-center">
                  <p className="text-xs text-muted-foreground mb-3">No study guide generated for this topic yet.</p>
                  <button
                    onClick={() => generateStudyGuide(sel.id, sel.title, sel.description)}
                    disabled={generatingGuide}
                    className="mx-auto flex items-center justify-center gap-2 rounded-xl gradient-brand px-4 py-2 text-xs font-bold text-primary-foreground shadow disabled:opacity-50"
                  >
                    <Sparkles className="h-3.5 w-3.5" />
                    {generatingGuide ? "Generating Explanation..." : "Generate AI Study Guide"}
                  </button>
                </div>
              )}

              {/* Prerequisite topic (if applicable) */}
              {prereqs.length > 0 && (
                <div className="mt-4 rounded-2xl border border-border bg-background p-3.5">
                  <p className="text-[10px] font-bold uppercase text-muted-foreground tracking-wider">Prerequisites</p>
                  <div className="mt-1.5 flex flex-wrap gap-1.5">
                    {prereqs.map(p => (
                      <span key={p.id} className="rounded-xl border border-border bg-muted/50 px-2.5 py-1 text-xs font-semibold text-foreground">
                        {p.title}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {sel.practice_task && (
                <div className="mt-4 rounded-2xl border border-border bg-background p-3">
                  <p className="text-[10px] font-bold uppercase text-muted-foreground">Practice</p>
                  <p className="mt-1 text-sm">{sel.practice_task}</p>
                </div>
              )}

              <NotesEditor initial={sel.notes ?? ""} onSave={(v) => saveNotes(sel.id, v)} />

              <div className="mt-4 grid grid-cols-2 gap-2">
                <Link to="/app/ai/exam" className="flex items-center justify-center gap-1.5 rounded-2xl border border-border py-2.5 text-xs font-bold">
                  <FileQuestion className="h-4 w-4" /> Quiz me
                </Link>
                <button onClick={() => toggleComplete(sel.id, sel.completed)} className={"flex items-center justify-center gap-1.5 rounded-2xl py-2.5 text-xs font-bold " + (sel.completed ? "border border-border" : "gradient-brand text-primary-foreground")}>
                  <Check className="h-4 w-4" /> {sel.completed ? "Mark incomplete" : "Mark complete"}
                </button>
              </div>
            </div>
          </div>
        );
      })()}
    </div>
  );
}

function Stat({ label, val, tint }: { label: string; val: number; tint: string }) {
  return (
    <div className={`flex-1 rounded-xl px-2 py-1.5 ${tint}`}>
      <p className="text-[9px] font-semibold uppercase opacity-75">{label}</p>
      <p className="text-sm font-black">{val}</p>
    </div>
  );
}

function ProgressRing({ pct }: { pct: number }) {
  const r = 16;
  const c = 2 * Math.PI * r;
  const off = c - (pct / 100) * c;
  return (
    <svg className="-rotate-90" width="40" height="40" viewBox="0 0 40 40">
      <circle cx="20" cy="20" r={r} className="stroke-muted" strokeWidth="3.5" fill="none" />
      <circle cx="20" cy="20" r={r} stroke="oklch(0.72 0.19 295)" strokeWidth="3.5" fill="none" strokeLinecap="round" strokeDasharray={c} strokeDashoffset={off} className="transition-all duration-700" />
    </svg>
  );
}

function NotesEditor({ initial, onSave }: { initial: string; onSave: (v: string) => void }) {
  const [v, setV] = useState(initial);
  const [dirty, setDirty] = useState(false);
  useEffect(() => { setV(initial); setDirty(false); }, [initial]);
  return (
    <div className="mt-4">
      <div className="flex items-center gap-1.5 text-[10px] font-bold uppercase text-muted-foreground">
        <StickyNote className="h-3 w-3" /> Notes
      </div>
      <textarea
        value={v}
        onChange={(e) => { setV(e.target.value); setDirty(true); }}
        onBlur={() => { if (dirty) { onSave(v); setDirty(false); } }}
        rows={3}
        placeholder="Your notes on this topic…"
        className="mt-1 w-full rounded-2xl border border-border bg-background px-3 py-2 text-sm outline-none focus:border-primary"
      />
    </div>
  );
}
