/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSkillsRouteImport } from './routes/_authenticated/app.skills'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppMissionsRouteImport } from './routes/_authenticated/app.missions'
import { Route as AuthenticatedAppLeaderboardRouteImport } from './routes/_authenticated/app.leaderboard'
import { Route as AuthenticatedAppRoomsIndexRouteImport } from './routes/_authenticated/app.rooms.index'
import { Route as AuthenticatedAppRoomsRoomIdRouteImport } from './routes/_authenticated/app.rooms.$roomId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSkillsRoute = AuthenticatedAppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMissionsRoute =
  AuthenticatedAppMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeaderboardRoute =
  AuthenticatedAppLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRoomsIndexRoute =
  AuthenticatedAppRoomsIndexRouteImport.update({
    id: '/rooms/',
    path: '/rooms/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRoomsRoomIdRoute =
  AuthenticatedAppRoomsRoomIdRouteImport.update({
    id: '/rooms/$roomId',
    path: '/rooms/$roomId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/app/missions': typeof AuthenticatedAppMissionsRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/skills': typeof AuthenticatedAppSkillsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/rooms/$roomId': typeof AuthenticatedAppRoomsRoomIdRoute
  '/app/rooms/': typeof AuthenticatedAppRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/app/missions': typeof AuthenticatedAppMissionsRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/skills': typeof AuthenticatedAppSkillsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/rooms/$roomId': typeof AuthenticatedAppRoomsRoomIdRoute
  '/app/rooms': typeof AuthenticatedAppRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/_authenticated/app/missions': typeof AuthenticatedAppMissionsRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/skills': typeof AuthenticatedAppSkillsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/rooms/$roomId': typeof AuthenticatedAppRoomsRoomIdRoute
  '/_authenticated/app/rooms/': typeof AuthenticatedAppRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/leaderboard'
    | '/app/missions'
    | '/app/notifications'
    | '/app/profile'
    | '/app/skills'
    | '/app/'
    | '/app/rooms/$roomId'
    | '/app/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/leaderboard'
    | '/app/missions'
    | '/app/notifications'
    | '/app/profile'
    | '/app/skills'
    | '/app'
    | '/app/rooms/$roomId'
    | '/app/rooms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/leaderboard'
    | '/_authenticated/app/missions'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/skills'
    | '/_authenticated/app/'
    | '/_authenticated/app/rooms/$roomId'
    | '/_authenticated/app/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/skills': {
      id: '/_authenticated/app/skills'
      path: '/skills'
      fullPath: '/app/skills'
      preLoaderRoute: typeof AuthenticatedAppSkillsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/missions': {
      id: '/_authenticated/app/missions'
      path: '/missions'
      fullPath: '/app/missions'
      preLoaderRoute: typeof AuthenticatedAppMissionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leaderboard': {
      id: '/_authenticated/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AuthenticatedAppLeaderboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rooms/': {
      id: '/_authenticated/app/rooms/'
      path: '/rooms'
      fullPath: '/app/rooms/'
      preLoaderRoute: typeof AuthenticatedAppRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rooms/$roomId': {
      id: '/_authenticated/app/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/app/rooms/$roomId'
      preLoaderRoute: typeof AuthenticatedAppRoomsRoomIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppLeaderboardRoute: typeof AuthenticatedAppLeaderboardRoute
  AuthenticatedAppMissionsRoute: typeof AuthenticatedAppMissionsRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppSkillsRoute: typeof AuthenticatedAppSkillsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppRoomsRoomIdRoute: typeof AuthenticatedAppRoomsRoomIdRoute
  AuthenticatedAppRoomsIndexRoute: typeof AuthenticatedAppRoomsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppLeaderboardRoute: AuthenticatedAppLeaderboardRoute,
  AuthenticatedAppMissionsRoute: AuthenticatedAppMissionsRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppSkillsRoute: AuthenticatedAppSkillsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppRoomsRoomIdRoute: AuthenticatedAppRoomsRoomIdRoute,
  AuthenticatedAppRoomsIndexRoute: AuthenticatedAppRoomsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
